/* References

   1. DOMContentLoaded:
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event
      - W3Schools: https://www.w3schools.com/jsref/event_domcontentloaded.asp
      - JavaScript.info: https://javascript.info/onload-ondomcontentloaded

   2. Selecting DOM Elements:
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById
      - W3Schools: https://www.w3schools.com/jsref/met_document_getelementbyid.asp
      - JavaScript.info: https://javascript.info/dom-nodes

   3. Event Listeners:
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
      - W3Schools: https://www.w3schools.com/jsref/met_element_addeventlistener.asp
      - JavaScript.info: https://javascript.info/introduction-browser-events

   4. Input Events:
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
      - W3Schools: https://www.w3schools.com/jsref/event_oninput.asp
      - JavaScript.info: https://javascript.info/input-events

   5. Class Manipulation (classList):
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
      - W3Schools: https://www.w3schools.com/jsref/prop_element_classlist.asp
      - JavaScript.info: https://javascript.info/classlist

   6. Focusing Elements:
      - MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
      - W3Schools: https://www.w3schools.com/jsref/met_html_focus.asp
      - JavaScript.info: https://javascript.info/focus-blur
*/

// -------------------------------
// TVBridge Header Script
// -------------------------------

document.addEventListener("DOMContentLoaded", () => {
  // -------------------------------
  // Client-Side Caching for Static Files
  // -------------------------------

  const CACHE_VERSION = 'v1';
  const CACHE_NAME = `tvbridge-cache-${CACHE_VERSION}`;

  if ("caches" in window) {
    const cacheFiles = [];

    // JS files
    const jsFiles = [
      'js/about-script.js',
      'js/contact-script.js',
      'js/header-style.js',
      'js/index-script.js',
      'js/listings-script.js',
      'js/theme.js',
      'js/tvguide-script.js'
    ];
    cacheFiles.push(...jsFiles);

    // CSS files
    const cssFiles = [
      'css/about-style.css',
      'css/contact-style.css',
      'css/global-style.css',
      'css/header-style.css',
      'css/index-style.css',
      'css/listings-style.css',
      'css/tvguide-style.css'
    ];
    cacheFiles.push(...cssFiles);

    // JSON files
    const jsonFiles = [
      'json/channels-ireland.json',
      'json/channels-uk.json',
      'json/custom-images.json',
      'json/pattern-mapping.json',
      'json/shows.json'
    ];
    cacheFiles.push(...jsonFiles);

    // Images in /images (manually listed)
	// GitHub doesn't allow server side caching. Adding images causes performance to decrease.
    // const imageFiles = [
	// 		'images/4seven.svg',
	// 		'images/5.svg',
	// 		'images/5Action.svg',
	// 		'images/5SELECT.svg',
	// 		'images/5STAR.svg',
	// 		'images/5STAR_+1.svg',
	// 		'images/5USA_+1.svg',
	// 		'images/5_+1.svg',
	// 		'images/5_HD.svg',
	// 		'images/5_USA.svg',
	// 		'images/71.png',
	// 		'images/7Lá.jpg',
	// 		'images/Aaj.png',
	// 		'images/Aastha_TV.png',
	// 		'images/Ad_Astra.png',
	// 		'images/Ahlebait_TV.png',
	// 		'images/Akaal_Channel.png',
	// 		'images/Alba_Today.png',
	// 		'images/Al_Jazeera_HD.svg',
	// 		'images/Animal_Planet.svg',
	// 		'images/Animal_Planet_+1.svg',
	// 		'images/Arirang_HD.svg',
	// 		'images/Arise_News.svg',
	// 		'images/ARY_Digital.png',
	// 		'images/ATN_Bangla.svg',
	// 		'images/B4U_Movies.png',
	// 		'images/B4U_Music.svg',
	// 		'images/Babytv.png',
	// 		'images/BBC_Alba_HD.svg',
	// 		'images/BBC_Asian_Network.svg',
	// 		'images/BBC_Four_HD.svg',
	// 		'images/BBC_News_HD.svg',
	// 		'images/BBC_One_HD.svg',
	// 		'images/BBC_Parliament_HD.svg',
	// 		'images/BBC_Radio_1.svg',
	// 		'images/BBC_Radio_1Xtra.svg',
	// 		'images/BBC_Radio_2.svg',
	// 		'images/BBC_Radio_3.svg',
	// 		'images/BBC_Radio_4.svg',
	// 		'images/BBC_Radio_4_Extra.svg',
	// 		'images/BBC_Radio_5_Live.svg',
	// 		'images/BBC_Radio_5_Live_Sports_Extra.svg',
	// 		'images/BBC_Radio_6_Music.svg',
	// 		'images/BBC_Radio_Cymru.svg',
	// 		'images/BBC_Radio_Cymru_2.svg',
	// 		'images/BBC_Radio_Foyle.svg',
	// 		'images/BBC_Radio_London.svg',
	// 		'images/BBC_Radio_nan_Gàidheal.svg',
	// 		'images/BBC_Radio_Scotland.svg',
	// 		'images/BBC_Radio_Ulster.svg',
	// 		'images/BBC_Radio_Wales.svg',
	// 		'images/BBC_Red_Button_HD.svg',
	// 		'images/BBC_Scotland_HD.svg',
	// 		'images/BBC_Sport_Studio.png',
	// 		'images/BBC_Three_HD.svg',
	// 		'images/BBC_Two_HD.svg',
	// 		'images/BBC_World_Service.svg',
	// 		'images/Best_Christmas_Music.png',
	// 		'images/Best_Direct.svg',
	// 		'images/BFBS_Radio.svg',
	// 		'images/Blaze.svg',
	// 		'images/Bloomberg_TV_HD.svg',
	// 		'images/Boomerang.svg',
	// 		'images/Boomerang_+1.svg',
	// 		'images/Boomerang_HD.svg',
	// 		'images/Capital.svg',
	// 		'images/Capital_XTRA.svg',
	// 		'images/Cartoonito.svg',
	// 		'images/Cartoon_Network.svg',
	// 		'images/Cartoon_Network_+1.svg',
	// 		'images/Cartoon_Network_HD_2010.svg',
	// 		'images/CBBC_HD.svg',
	// 		'images/CBeebies_HD.svg',
	// 		'images/Challenge.png',
	// 		'images/Channels_24.png',
	// 		'images/Channel_4_+1.svg',
	// 		'images/Channel_4_HD.svg',
	// 		'images/Channel_S.svg',
	// 		'images/Channel_U.png',
	// 		'images/Christmas_24+.svg',
	// 		'images/Christmas_24.svg',
	// 		'images/Classic_FM.svg',
	// 		'images/Classic_Music_Hits.png',
	// 		'images/Clubland.svg',
	// 		'images/Club_MTV.svg',
	// 		'images/CNBC_HD.svg',
	// 		'images/CNN_HD.svg',
	// 		'images/Colors.svg',
	// 		'images/Colors_Cineplex.png',
	// 		'images/Colors_Gujarati.svg',
	// 		'images/Colors_HD.svg',
	// 		'images/Colors_Rishtey.png',
	// 		'images/Comedy_Central.svg',
	// 		'images/Comedy_Central_+1.svg',
	// 		'images/Comedy_Central_Extra.svg',
	// 		'images/Comedy_Central_HD.svg',
	// 		'images/Court_TV.svg',
	// 		'images/Crime+Investigation.svg',
	// 		'images/Crime+Investigation_+1.svg',
	// 		'images/Crime+Investigation_HD.svg',
	// 		'images/Cruise1st.tv.svg',
	// 		'images/Cruise_TV.png',
	// 		'images/Cúla4.png',
	// 		'images/Cúla4_HD.svg',
	// 		'images/Daystar_HD.svg',
	// 		'images/Deen_TV.png',
	// 		'images/Discovery_+1.svg',
	// 		'images/Discovery_Channel.svg',
	// 		'images/Discovery_HD.svg',
	// 		'images/Discovery_History.png',
	// 		'images/Discovery_History_Plus_1.png',
	// 		'images/Discovery_Science.svg',
	// 		'images/Discovery_Science_+1.svg',
	// 		'images/Discovery_Turbo.svg',
	// 		'images/Discovery_Turbo_+1.svg',
	// 		'images/Disney_Jr.svg',
	// 		'images/Disney_Junior_Ariel.png',
	// 		'images/DMAX_+1.svg',
	// 		'images/DMAX_UK.svg',
	// 		'images/DM_News_English.png',
	// 		'images/Doctor_Who.png',
	// 		'images/Dunamis_TV.png',
	// 		'images/Dáil_Éireann.png',
	// 		'images/E4.svg',
	// 		'images/E4_+1.svg',
	// 		'images/E4_Extra.svg',
	// 		'images/E4_HD.svg',
	// 		'images/Eman_Channel.svg',
	// 		'images/Entertainment_News_on_5.png',
	// 		'images/Euronews.svg',
	// 		'images/EU_flag_long.png',
	// 		'images/EWTN.svg',
	// 		'images/extended-family.jpg',
	// 		'images/F1.png',
	// 		'images/Faith_UK.svg',
	// 		'images/Faith_World_TV.png',
	// 		'images/fav-icon.ico',
	// 		'images/FIFA.png',
	// 		'images/Film4.svg',
	// 		'images/Film4_+1.svg',
	// 		'images/Film4_HD.svg',
	// 		'images/Food_Network.svg',
	// 		'images/Food_Network_+1.svg',
	// 		'images/France24.png',
	// 		'images/France_24_HD.png',
	// 		'images/GB_News_HD.svg',
	// 		'images/Gems_TV_HD.png',
	// 		'images/Geo_News_UK.svg',
	// 		'images/Geo_TV.png',
	// 		'images/GINX_Esports_TV_HD.svg',
	// 		'images/GOD_TV.svg',
	// 		'images/Gold_Radio.svg',
	// 		'images/Good_News.png',
	// 		'images/Gordon_Ramsay.png',
	// 		'images/GREAT!_Action.svg',
	// 		'images/GREAT!_Action_+1.svg',
	// 		'images/GREAT!_Christmas.svg',
	// 		'images/GREAT!_Christmas_+1.svg',
	// 		'images/GREAT!_Mystery.svg',
	// 		'images/GREAT!_Mystery_+1.svg',
	// 		'images/GREAT!_Romance.svg',
	// 		'images/GREAT!_Romance_+1.svg',
	// 		'images/GREAT!_TV.svg',
	// 		'images/GREAT!_TV_+1.svg',
	// 		'images/Heart_80s.svg',
	// 		'images/Heart_90s.svg',
	// 		'images/Heart_Dance.png',
	// 		'images/Heart_Radio.svg',
	// 		'images/HGTV.svg',
	// 		'images/HGTV_+1.svg',
	// 		'images/High_Street_TV.svg',
	// 		'images/HobbyMaker.svg',
	// 		'images/Horse_Racing.png',
	// 		'images/Hum_Europe.svg',
	// 		'images/Hum_Masala.png',
	// 		'images/Ideal_World.svg',
	// 		'images/Investigation_Discovery.svg',
	// 		'images/Investigation_Discovery_+1.svg',
	// 		'images/ION_TV.png',
	// 		'images/IQRA_Bangla.svg',
	// 		'images/IQRA_TV.svg',
	// 		'images/Islam_Channel.svg',
	// 		'images/Islam_Channel_Bangla.svg',
	// 		'images/Islam_Channel_Urdu.svg',
	// 		'images/Islam_TV.svg',
	// 		'images/ITV1_+1.svg',
	// 		'images/ITV1_HD.svg',
	// 		'images/ITV2_+1.svg',
	// 		'images/ITV2_HD.svg',
	// 		'images/ITV3_+1.svg',
	// 		'images/ITV3_HD.svg',
	// 		'images/ITV4_+1.svg',
	// 		'images/ITV4_HD.svg',
	// 		'images/ITV_Quiz_HD.svg',
	// 		'images/ITV_Racing.png',
	// 		'images/Jasmine_Harman.png',
	// 		'images/Jewellery_Maker.svg',
	// 		'images/Kanshi_TV.png',
	// 		'images/LBC.svg',
	// 		'images/LBC_News.svg',
	// 		'images/Legend.svg',
	// 		'images/Legend_Xtra.svg',
	// 		'images/Legend_Xtra_+1.svg',
	// 		'images/LENNON80.png',
	// 		'images/LFCTV.svg',
	// 		'images/logo.png',
	// 		'images/logo.svg',
	// 		'images/London_News.png',
	// 		'images/London_TV.png',
	// 		'images/Loveworld_TV_HD.png',
	// 		'images/Madani_Channel.png',
	// 		'images/MATV_National.png',
	// 		'images/Mickeys_Great_Clubhouse_Hunt.png',
	// 		'images/Minnies_Bow_Toons.png',
	// 		'images/More4.svg',
	// 		'images/More4_+1.svg',
	// 		'images/More4_HD.svg',
	// 		'images/Movies_24+.svg',
	// 		'images/Movies_24.svg',
	// 		'images/MTA1_WORLD_HD.svg',
	// 		'images/MTV.svg',
	// 		'images/MTV_80s.png',
	// 		'images/MTV_80s_(Europe)_2020.svg',
	// 		'images/MTV_90s.svg',
	// 		'images/MTV_HD_UK.svg',
	// 		'images/MTV_Love.png',
	// 		'images/MTV_Music.svg',
	// 		'images/MTV_Pride.svg',
	// 		'images/MTV_Summer.svg',
	// 		'images/MTV_Xmas.svg',
	// 		'images/Music_Live.png',
	// 		'images/Must_Have_Ideas.png',
	// 		'images/MUTV_HD.svg',
	// 		'images/National_Geographic.svg',
	// 		'images/National_Geographic_+1.svg',
	// 		'images/National_Geographic_HD.svg',
	// 		'images/National_Geographic_Wild.svg',
	// 		'images/Nationwide.png',
	// 		'images/NDTV_World.svg',
	// 		'images/Newyddion_S4C.png',
	// 		'images/New_Vision_TV.png',
	// 		'images/NFL.png',
	// 		'images/NHK_World_HD.svg',
	// 		'images/Nickelodeon.svg',
	// 		'images/Nickelodeon_+1.svg',
	// 		'images/Nickelodeon_HD.svg',
	// 		'images/Nicktoons.svg',
	// 		'images/Nick_Horrid_Henry.png',
	// 		'images/Nick_Jr..svg',
	// 		'images/Nick_Jr._+1.png',
	// 		'images/Nick_Jr._HD.png',
	// 		'images/Nick_Jr._Paw_Patrol.svg',
	// 		'images/Nick_Jr._Peppa.png',
	// 		'images/Nick_Jr._Too.png',
	// 		'images/Nick_Loud_House.png',
	// 		'images/Nick_SpongeBob.png',
	// 		'images/Night_Vision.png',
	// 		'images/Noor_TV.png',
	// 		'images/Now_70s.png',
	// 		'images/Now_80s.png',
	// 		'images/Now_90s.png',
	// 		'images/Now_90s_&_00s.png',
	// 		'images/NOW_Christmas.png',
	// 		'images/NOW_Rock.png',
	// 		'images/NTD.svg',
	// 		'images/NTV_UK.svg',
	// 		'images/Nuacht_RTÉ.png',
	// 		'images/Oireachtas_TV.svg',
	// 		'images/Panjab_Broadcasting_Channel.png',
	// 		'images/Panjab_Radio.svg',
	// 		'images/Panjab_TV.png',
	// 		'images/PBS_America.svg',
	// 		'images/Phoenix_Chinese_News_and_Entertainment.svg',
	// 		'images/Pitaara.svg',
	// 		'images/Play-ojo.png',
	// 		'images/Politics_London.png',
	// 		'images/Politics_Punjab.png',
	// 		'images/Pop.svg',
	// 		'images/Pop_+1.svg',
	// 		'images/Premier_Sports_1_HD.svg',
	// 		'images/Premier_Sports_2_HD.svg',
	// 		'images/Programmes.png',
	// 		'images/PTC_Punjabi.png',
	// 		'images/QTV_Religious.png',
	// 		'images/Quest.svg',
	// 		'images/Quest_+1.svg',
	// 		'images/Quest_HD.svg',
	// 		'images/Quest_Red.svg',
	// 		'images/Quest_Red_+1.svg',
	// 		'images/Quran.png',
	// 		'images/QVC_Beauty.svg',
	// 		'images/QVC_Extra.svg',
	// 		'images/QVC_HD.svg',
	// 		'images/QVC_Style_HD.svg',
	// 		'images/Racing_TV.svg',
	// 		'images/Racing_TV_HD.svg',
	// 		'images/Radio_X.png',
	// 		'images/Ransom_79.png',
	// 		'images/Really.svg',
	// 		'images/Revelation.svg',
	// 		'images/Rewind_TV_(UK).svg',
	// 		'images/RTE2_+1.svg',
	// 		'images/RTE2_HD.svg',
	// 		'images/RTE_News_promo.png',
	// 		'images/RTE_One_+1.svg',
	// 		'images/RTE_One_HD.svg',
	// 		'images/RTÉjr.svg',
	// 		'images/RTÉ_2FM.svg',
	// 		'images/RTÉ_Lyric_FM.svg',
	// 		'images/RTÉ_News.svg',
	// 		'images/RTÉ_Radio_1.svg',
	// 		'images/RTÉ_Raidió_na_Gaeltachta.svg',
	// 		'images/S4C.svg',
	// 		'images/S4C_HD.svg',
	// 		'images/Sangat_Television.svg',
	// 		'images/Sanskar_TV.png',
	// 		'images/Shop_Unlimited.png',
	// 		'images/Sikh_Channel.png',
	// 		'images/Sky.svg',
	// 		'images/Sky_Accessibility.png',
	// 		'images/Sky_Arts.png',
	// 		'images/Sky_Arts_HD.png',
	// 		'images/Sky_Atlantic.svg',
	// 		'images/Sky_Atlantic_+1.svg',
	// 		'images/Sky_Atlantic_HD.svg',
	// 		'images/Sky_Cinema.svg',
	// 		'images/Sky_Cinema_00s_HD.png',
	// 		'images/Sky_Cinema_10s_HD.png',
	// 		'images/Sky_Cinema_2025_Recap_HD.png',
	// 		'images/Sky_Cinema_20s_HD.png',
	// 		'images/Sky_Cinema_5_Star_Movies_HD.png',
	// 		'images/Sky_Cinema_80s_HD.png',
	// 		'images/Sky_Cinema_90s_HD.png',
	// 		'images/Sky_Cinema_Action_HD.svg',
	// 		'images/Sky_Cinema_Action_Men_HD.png',
	// 		'images/Sky_Cinema_Adam_Sandler_HD.png',
	// 		'images/Sky_Cinema_Adventure_HD.svg',
	// 		'images/Sky_Cinema_Alien_HD.svg',
	// 		'images/Sky_Cinema_Animation_HD.svg',
	// 		'images/Sky_Cinema_Antiheroes_HD.png',
	// 		'images/Sky_Cinema_Apocalyptic_HD.png',
	// 		'images/Sky_Cinema_April_Fools_HD.png',
	// 		'images/Sky_Cinema_Assassins_HD.svg',
	// 		'images/Sky_Cinema_Awards_Season_HD.png',
	// 		'images/Sky_Cinema_Award_Winners_HD.png',
	// 		'images/Sky_Cinema_Back_to_School_HD.svg',
	// 		'images/Sky_Cinema_Back_to_the_Future_HD.png',
	// 		'images/Sky_Cinema_Bank_Holiday_HD.png',
	// 		'images/Sky_Cinema_Batman_HD.png',
	// 		'images/Sky_Cinema_Best_of_2020_HD.png',
	// 		'images/Sky_Cinema_Best_Of_HD.svg',
	// 		'images/Sky_Cinema_Best_of_the_00s_HD.svg',
	// 		'images/Sky_Cinema_Best_of_the_80s_HD.svg',
	// 		'images/Sky_Cinema_Best_of_the_90s_HD.svg',
	// 		'images/Sky_Cinema_Blockbusters_HD.svg',
	// 		'images/Sky_Cinema_Book_Day_HD.svg',
	// 		'images/Sky_Cinema_Book_To_Screen_HD.png',
	// 		'images/Sky_Cinema_Bourne_HD.svg',
	// 		'images/Sky_Cinema_Bridget_Jones_HD.png',
	// 		'images/Sky_Cinema_British_Icons_HD.svg',
	// 		'images/Sky_Cinema_Brits_HD.svg',
	// 		'images/Sky_Cinema_Buddy_Films_HD.png',
	// 		'images/Sky_Cinema_Christmas_HD.svg',
	// 		'images/Sky_Cinema_Classics_HD.png',
	// 		'images/Sky_Cinema_Comedy_HD.svg',
	// 		'images/Sky_Cinema_Cops_&_Robbers_HD.svg',
	// 		'images/Sky_Cinema_Cornetto_HD.svg',
	// 		'images/Sky_Cinema_Crime_HD.png',
	// 		'images/Sky_Cinema_Cult_Classics_HD.svg',
	// 		'images/Sky_Cinema_Da_Vinci_HD.png',
	// 		'images/Sky_Cinema_DC_HD.png',
	// 		'images/Sky_Cinema_DC_Heroes_HD.png',
	// 		'images/Sky_Cinema_Denzel_Washington_HD.png',
	// 		'images/Sky_Cinema_Disney_HD.svg',
	// 		'images/Sky_Cinema_Divergent_HD.svg',
	// 		'images/Sky_Cinema_Drama_HD.svg',
	// 		'images/Sky_Cinema_Dystopia_HD.svg',
	// 		'images/Sky_Cinema_Edgar_Wright_HD.svg',
	// 		'images/Sky_Cinema_Elvis_HD.png',
	// 		'images/Sky_Cinema_Epics_HD.svg',
	// 		'images/Sky_Cinema_Epic_Worlds_HD.png',
	// 		'images/Sky_Cinema_Exclusives_HD.png',
	// 		'images/Sky_Cinema_Fairy_Tales_HD.png',
	// 		'images/Sky_Cinema_Family_HD.svg',
	// 		'images/Sky_Cinema_Fantasy_HD.png',
	// 		'images/Sky_Cinema_Fast_&_Furious_HD.png',
	// 		'images/Sky_Cinema_Fast_HD.png',
	// 		'images/Sky_Cinema_Favourites_HD.png',
	// 		'images/Sky_Cinema_Feel_Good_HD.svg',
	// 		'images/Sky_Cinema_Gangsters_HD.svg',
	// 		'images/Sky_Cinema_Gems_HD.png',
	// 		'images/Sky_Cinema_Godfather_HD.svg',
	// 		'images/Sky_Cinema_Greats_HD.png',
	// 		'images/Sky_Cinema_Halloween_HD.svg',
	// 		'images/Sky_Cinema_Hanks-Giving_HD.svg',
	// 		'images/Sky_Cinema_Harry_Potter_HD.png',
	// 		'images/Sky_Cinema_HD.png',
	// 		'images/Sky_Cinema_Heists_HD.png',
	// 		'images/Sky_Cinema_Heroes_HD.png',
	// 		'images/Sky_Cinema_Hits_HD.png',
	// 		'images/Sky_Cinema_Horror_HD.png',
	// 		'images/Sky_Cinema_Icons_HD.png',
	// 		'images/Sky_Cinema_Indiana_Jones_HD.svg',
	// 		'images/Sky_Cinema_Jaws_HD.png',
	// 		'images/Sky_Cinema_Jokers_HD.svg',
	// 		'images/Sky_Cinema_Julia_Roberts_HD.png',
	// 		'images/Sky_Cinema_Jurassic_Park_HD.svg',
	// 		'images/Sky_Cinema_Jurassic_World_HD.svg',
	// 		'images/Sky_Cinema_Karate_Kid_HD.png',
	// 		'images/Sky_Cinema_Kids_Books_HD.svg',
	// 		'images/Sky_Cinema_Killer_Movies_HD.svg',
	// 		'images/Sky_Cinema_Kung_Fu_Panda_HD.png',
	// 		'images/Sky_Cinema_Lord_of_the_Rings_HD.png',
	// 		'images/Sky_Cinema_Magic_HD.svg',
	// 		'images/Sky_Cinema_Martial_Arts_HD.png',
	// 		'images/Sky_Cinema_Matt_Damon_HD.png',
	// 		'images/Sky_Cinema_Megahits_HD.svg',
	// 		'images/Sky_Cinema_Men_In_Black_HD.png',
	// 		'images/Sky_Cinema_Middle_Earth_HD.png',
	// 		'images/Sky_Cinema_Misfits_HD.svg',
	// 		'images/Sky_Cinema_Mission_Impossible_HD.png',
	// 		'images/Sky_Cinema_Monsters_HD.png',
	// 		'images/Sky_Cinema_Musicals_HD.png',
	// 		'images/Sky_Cinema_Music_HD.png',
	// 		'images/Sky_Cinema_Must_See_Movies_HD.png',
	// 		'images/Sky_Cinema_Mystery_HD.png',
	// 		'images/Sky_Cinema_Originals_HD.png',
	// 		'images/Sky_Cinema_Original_vs._Remake_HD.png',
	// 		'images/Sky_Cinema_Oscars_HD.png',
	// 		'images/Sky_Cinema_Pets_HD.png',
	// 		'images/Sky_Cinema_Pirates_of_the_Caribbean_HD.png',
	// 		'images/Sky_Cinema_Pitch_Perfect_HD.png',
	// 		'images/Sky_Cinema_Pixar_HD.png',
	// 		'images/Sky_Cinema_Premieren_+24_HD.svg',
	// 		'images/Sky_Cinema_Premieren_HD.svg',
	// 		'images/Sky_Cinema_Premiere_HD.svg',
	// 		'images/Sky_Cinema_Pride_HD.png',
	// 		'images/Sky_Cinema_Race_Against_Time_HD.png',
	// 		'images/Sky_Cinema_Resident_Evil_HD.png',
	// 		'images/Sky_Cinema_Revenge_HD.png',
	// 		'images/Sky_Cinema_Road_Movies_HD.png',
	// 		'images/Sky_Cinema_Romance_HD.svg',
	// 		'images/Sky_Cinema_Rom_Coms_HD.svg',
	// 		'images/Sky_Cinema_School\'s_Out_HD.png',
	// 		'images/Sky_Cinema_Sci-Fi_&_Horror_HD.png',
	// 		'images/Sky_Cinema_Sci-Fi_HD.png',
	// 		'images/Sky_Cinema_Select_HD.png',
	// 		'images/Sky_Cinema_Sky-Fi_HD.png',
	// 		'images/Sky_Cinema_Slasher_HD.svg',
	// 		'images/Sky_Cinema_Space_Week_HD.png',
	// 		'images/Sky_Cinema_SpecialL_HD.svg',
	// 		'images/Sky_Cinema_Spider-Man_HD.svg',
	// 		'images/Sky_Cinema_Spies_HD.png',
	// 		'images/Sky_Cinema_Spooky_HD.png',
	// 		'images/Sky_Cinema_Star_Trek_HD.png',
	// 		'images/Sky_Cinema_Star_Wars_HD.png',
	// 		'images/Sky_Cinema_Stunts_HD.png',
	// 		'images/Sky_Cinema_Summer_Scares_HD.png',
	// 		'images/Sky_Cinema_Superheroes_HD.png',
	// 		'images/Sky_Cinema_Superman_HD.png',
	// 		'images/Sky_Cinema_Supernatural_HD.svg',
	// 		'images/Sky_Cinema_The_Hobbit_HD.png',
	// 		'images/Sky_Cinema_The_Matrix_HD.png',
	// 		'images/Sky_Cinema_Thriller_HD.png',
	// 		'images/Sky_Cinema_Tom_Cruise_HD.svg',
	// 		'images/Sky_Cinema_Tom_Hanks_HD.png',
	// 		'images/Sky_Cinema_Transformers_HD.png',
	// 		'images/Sky_Cinema_True_Stories_HD.svg',
	// 		'images/Sky_Cinema_Twilight_HD.svg',
	// 		'images/Sky_Cinema_Ultimate_Action_HD.svg',
	// 		'images/Sky_Cinema_Undead_HD.svg',
	// 		'images/Sky_Cinema_Valentines_HD.png',
	// 		'images/Sky_Cinema_Vengeance_HD.svg',
	// 		'images/Sky_Cinema_Villains_HD.svg',
	// 		'images/Sky_Cinema_Weddings_HD.png',
	// 		'images/Sky_Cinema_Westerns_HD.png',
	// 		'images/Sky_Cinema_Will_Smith_HD.png',
	// 		'images/Sky_Cinema_Wizarding_World_HD.svg',
	// 		'images/Sky_Cinema_Women_In_Film_HD.svg',
	// 		'images/Sky_Comedy.svg',
	// 		'images/Sky_Comedy_HD.svg',
	// 		'images/Sky_Crime.svg',
	// 		'images/Sky_Crime_+1.svg',
	// 		'images/Sky_Crime_HD.svg',
	// 		'images/Sky_Documentaries.svg',
	// 		'images/Sky_Documentaries_HD.svg',
	// 		'images/Sky_History.svg',
	// 		'images/Sky_History2_HD.svg',
	// 		'images/Sky_History_HD.svg',
	// 		'images/Sky_Kids_HD.svg',
	// 		'images/Sky_Max.svg',
	// 		'images/Sky_Max_HD.svg',
	// 		'images/Sky_Mix_HD.svg',
	// 		'images/Sky_Nature.svg',
	// 		'images/Sky_Nature_HD.svg',
	// 		'images/Sky_News.svg',
	// 		'images/Sky_News_Arabia.svg',
	// 		'images/Sky_News_HD.svg',
	// 		'images/Sky_News_listing.png',
	// 		'images/Sky_Replay.svg',
	// 		'images/Sky_Sci-Fi.svg',
	// 		'images/Sky_Sci-Fi_HD.svg',
	// 		'images/Sky_Showcase.svg',
	// 		'images/Sky_Showcase_+1.svg',
	// 		'images/Sky_Showcase_HD.svg',
	// 		'images/Sky_Sports+.svg',
	// 		'images/Sky_Sports+_HD.svg',
	// 		'images/Sky_Sports.svg',
	// 		'images/Sky_Sports_Action_HD.svg',
	// 		'images/Sky_Sports_Arena_HD.svg',
	// 		'images/Sky_Sports_Box_Office_HD.svg',
	// 		'images/Sky_Sports_Cricket.svg',
	// 		'images/Sky_Sports_Cricket_HD.svg',
	// 		'images/Sky_Sports_Cricket_World_Cup_HD.svg',
	// 		'images/Sky_Sports_Darts_HD.svg',
	// 		'images/Sky_Sports_F1.svg',
	// 		'images/Sky_Sports_F1_HD.svg',
	// 		'images/Sky_Sports_Football.svg',
	// 		'images/Sky_Sports_Football_HD.svg',
	// 		'images/Sky_Sports_Golf.svg',
	// 		'images/Sky_Sports_Golf_HD.svg',
	// 		'images/Sky_Sports_HD.png',
	// 		'images/Sky_Sports_Main_Event.svg',
	// 		'images/Sky_Sports_Main_Event_HD.svg',
	// 		'images/Sky_Sports_Masters_HD.svg',
	// 		'images/Sky_Sports_Mix.svg',
	// 		'images/Sky_Sports_Mix_HD.svg',
	// 		'images/Sky_Sports_Netball_HD.png',
	// 		'images/Sky_Sports_News.svg',
	// 		'images/Sky_Sports_News_HD.svg',
	// 		'images/Sky_Sports_News_Studio.png',
	// 		'images/Sky_Sports_NFL.svg',
	// 		'images/Sky_Sports_NFL_HD.svg',
	// 		'images/Sky_Sports_Premier_League.svg',
	// 		'images/Sky_Sports_Premier_League_HD.svg',
	// 		'images/Sky_Sports_Racing_HD.svg',
	// 		'images/Sky_Sports_Ryder_Cup_HD.svg',
	// 		'images/Sky_Sports_Tennis.svg',
	// 		'images/Sky_Sports_Tennis_HD.svg',
	// 		'images/Sky_Sports_The_Ashes_HD.png',
	// 		'images/Sky_Sports_The_Hundred_HD.svg',
	// 		'images/Sky_Sports_The_Lions_HD.svg',
	// 		'images/Sky_Sports_The_Open_HD.svg',
	// 		'images/Sky_Sports_The_Players_HD.svg',
	// 		'images/Sky_Sports_USA_HD.png',
	// 		'images/Sky_Sports_US_Open_HD.png',
	// 		'images/Sky_Witness.svg',
	// 		'images/Sky_Witness_+1.svg',
	// 		'images/Sky_Witness_HD.svg',
	// 		'images/Smooth_Radio.svg',
	// 		'images/Snooker.png',
	// 		'images/SonLife_Broadcasting_Network.png',
	// 		'images/Sony_Entertainment_Television.png',
	// 		'images/Sony_Entertainment_Television_HD.png',
	// 		'images/Sony_Max.png',
	// 		'images/Sony_Max_2.png',
	// 		'images/Sony_Max_HD.png',
	// 		'images/Sony_MAX_India_HD.png',
	// 		'images/Sony_Max_+1.png',
	// 		'images/Sony_MAX_HD.png',
	// 		'images/Sony_Max.png',
	// 		'images/Sony_Max_2.png',
	// 		'images/Sony_Max_HD.png',
	// 		'images/Sony_SAB.png',
	// 		'images/STV_(Scotland).svg',
	// 		'images/STV_HD.png',
	// 		'images/Takbeer_TV.png',
	// 		'images/Talking_Pictures_TV.svg',
	// 		'images/Talksport.svg',
	// 		'images/TBNUK.svg',
	// 		'images/Teleshopping.png',
	// 		'images/TG4_HD.svg',
	// 		'images/That\'s_60s.png',
	// 		'images/That\'s_60s_block.png',
	// 		'images/That\'s_70s.png',
	// 		'images/That\'s_80s.png',
	// 		'images/That\'s_80s_block.png',
	// 		'images/That\'s_Christmas.png',
	// 		'images/That\'s_Dance.png',
	// 		'images/That\'s_Melody.svg',
	// 		'images/That\'s_Oldies.png',
	// 		'images/That\'s_Pride.png',
	// 		'images/That\'s_Rock.svg',
	// 		'images/That\'s_Summer.png',
	// 		'images/That\'s_TV.png',
	// 		'images/That\'s_TV_2.svg',
	// 		'images/That\'s_TV_3.svg',
	// 		'images/That\'s_TV_Gold.png',
	// 		'images/That\'s_TV_Xmas.png',
	// 		'images/This_Morning_Friday.png',
	// 		'images/Tiny_Pop.svg',
	// 		'images/Tiny_Pop_+1.svg',
	// 		'images/TJC_HD.png',
	// 		'images/TLC.svg',
	// 		'images/TLC_+1.svg',
	// 		'images/TLC_HD.svg',
	// 		'images/TNT_Sports_1.svg',
	// 		'images/TNT_Sports_10.svg',
	// 		'images/TNT_Sports_1_HD.svg',
	// 		'images/TNT_Sports_2.svg',
	// 		'images/TNT_Sports_2_HD.svg',
	// 		'images/TNT_Sports_3.svg',
	// 		'images/TNT_Sports_3_HD.svg',
	// 		'images/TNT_Sports_4.svg',
	// 		'images/TNT_Sports_4_HD.svg',
	// 		'images/TNT_Sports_5_HD.svg',
	// 		'images/TNT_Sports_6.svg',
	// 		'images/TNT_Sports_7.svg',
	// 		'images/TNT_Sports_8.svg',
	// 		'images/TNT_Sports_9.svg',
	// 		'images/TNT_Sports_Box_Office_2_HD.svg',
	// 		'images/TNT_Sports_Box_Office_HD.svg',
	// 		'images/Together_TV.svg',
	// 		'images/Travelxp.svg',
	// 		'images/TRT_World.svg',
	// 		'images/TRT_World_HD.svg',
	// 		'images/True_Crime.svg',
	// 		'images/True_Crime_+1.svg',
	// 		'images/True_Crime_Xtra.svg',
	// 		'images/TVC_News.png',
	// 		'images/TV_One.png',
	// 		'images/TV_Warehouse.svg',
	// 		'images/U&Alibi.svg',
	// 		'images/U&Alibi_+1.svg',
	// 		'images/U&Alibi_HD.svg',
	// 		'images/U&Dave.svg',
	// 		'images/U&DaveJaVu.svg',
	// 		'images/U&Dave_HD.svg',
	// 		'images/U&Drama.svg',
	// 		'images/U&Drama_+1.svg',
	// 		'images/U&Eden.svg',
	// 		'images/U&Eden_+1.svg',
	// 		'images/U&Gold.svg',
	// 		'images/U&Gold_+1.svg',
	// 		'images/U&Gold_HD.svg',
	// 		'images/U&W.svg',
	// 		'images/U&W_+1.svg',
	// 		'images/U&Yesterday.svg',
	// 		'images/U&Yesterday_+1.svg',
	// 		'images/U&Yesterday_HD.svg',
	// 		'images/Unofficial_Home_Alone.png',
	// 		'images/Utsav_Bharat.svg',
	// 		'images/Utsav_Gold.svg',
	// 		'images/Utsav_Gold_HD.svg',
	// 		'images/Utsav_Plus.svg',
	// 		'images/Utsav_Plus_HD.svg',
	// 		'images/UTV_HD.svg',
	// 		'images/UTV_Live.png',
	// 		'images/Virgin_Media_Four_HD.svg',
	// 		'images/Virgin_Media_One_+1.svg',
	// 		'images/Virgin_Media_One_HD.svg',
	// 		'images/Virgin_Media_Three.svg',
	// 		'images/Virgin_Media_Two_HD.svg',
	// 		'images/Virgin_Radio.png',
	// 		'images/Walter_Presents.png',
	// 		'images/Weather.png',
	// 		'images/When_Classic.png',
	// 		'images/WION.svg',
	// 		'images/WRN_Europe.svg',
	// 		'images/Zee_Cinema.svg',
	// 		'images/Zee_Punjabi_(UK)_2024.png',
	// 		'images/Zee_TV.svg',
	// 		'images/Zee_TV_HD_2017.svg',
    // ];
    // cacheFiles.push(...imageFiles);

    // Open the cache and add all files
    caches.open(CACHE_NAME).then((cache) => {
      cache.addAll(cacheFiles).catch((err) => {
        console.warn('Some files could not be cached:', err);
      });
    });
  }
});

